#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v12
# autospec commit: 381dfd8
#
Name     : qt6multimedia
Version  : 6.7.2
Release  : 19
URL      : https://download.qt.io/official_releases/qt/6.7/6.7.2/submodules/qtmultimedia-everywhere-src-6.7.2.zip
Source0  : https://download.qt.io/official_releases/qt/6.7/6.7.2/submodules/qtmultimedia-everywhere-src-6.7.2.zip
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause GPL-2.0 GPL-3.0 LGPL-2.1 LGPL-3.0 MIT MPL-2.0
Requires: qt6multimedia-lib = %{version}-%{release}
Requires: qt6multimedia-license = %{version}-%{release}
BuildRequires : Vulkan-Headers-dev
BuildRequires : alsa-lib-dev
BuildRequires : buildreq-cmake
BuildRequires : extra-cmake-modules pkgconfig(egl)
BuildRequires : extra-cmake-modules pkgconfig(libpulse)
BuildRequires : glibc-dev
BuildRequires : openssl-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : qt6base-dev
BuildRequires : qt6declarative-dev
BuildRequires : qt6shadertools-dev
BuildRequires : qtbase-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
These files have been automatically generated using:
$./generate_hrtf_assets.py hrtf_assets.iad generated

%package dev
Summary: dev components for the qt6multimedia package.
Group: Development
Requires: qt6multimedia-lib = %{version}-%{release}
Provides: qt6multimedia-devel = %{version}-%{release}
Requires: qt6multimedia = %{version}-%{release}

%description dev
dev components for the qt6multimedia package.


%package lib
Summary: lib components for the qt6multimedia package.
Group: Libraries
Requires: qt6multimedia-license = %{version}-%{release}

%description lib
lib components for the qt6multimedia package.


%package license
Summary: license components for the qt6multimedia package.
Group: Default

%description license
license components for the qt6multimedia package.


%prep
%setup -q -n qtmultimedia-everywhere-src-6.7.2
cd %{_builddir}/qtmultimedia-everywhere-src-6.7.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1718984025
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1718984025
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/qt6multimedia
cp %{_builddir}/qtmultimedia-everywhere-src-%{version}/LICENSES/BSD-3-Clause.txt %{buildroot}/usr/share/package-licenses/qt6multimedia/79453f55fa8ee32d7b95581473edcbfd043e088f || :
cp %{_builddir}/qtmultimedia-everywhere-src-%{version}/LICENSES/GPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/qt6multimedia/dc8f2e570bf431427dbc3bab9d4d551b53a60208 || :
cp %{_builddir}/qtmultimedia-everywhere-src-%{version}/LICENSES/GPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/qt6multimedia/7713a1753ce88f2c7e6b054ecc8e4c786df76300 || :
cp %{_builddir}/qtmultimedia-everywhere-src-%{version}/LICENSES/LGPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/qt6multimedia/c70af14df11e3908dfc10397b1ba4b1f346661f3 || :
cp %{_builddir}/qtmultimedia-everywhere-src-%{version}/LICENSES/MIT.txt %{buildroot}/usr/share/package-licenses/qt6multimedia/793b93301a29a830d8b40b3cbfaedec58193a291 || :
cp %{_builddir}/qtmultimedia-everywhere-src-%{version}/examples/multimedia/spectrum/3rdparty/fftreal/license.txt %{buildroot}/usr/share/package-licenses/qt6multimedia/2bc71d48cf227830dff9a8d2a09ae79dbc997507 || :
cp %{_builddir}/qtmultimedia-everywhere-src-%{version}/src/3rdparty/eigen/COPYING.BSD %{buildroot}/usr/share/package-licenses/qt6multimedia/edf9e52983e1225976cdb134d78a286224acc9f3 || :
cp %{_builddir}/qtmultimedia-everywhere-src-%{version}/src/3rdparty/eigen/COPYING.MPL2 %{buildroot}/usr/share/package-licenses/qt6multimedia/9cf097120d3d9eea0e9790d7d44ae80e6231a35a || :
cp %{_builddir}/qtmultimedia-everywhere-src-%{version}/src/3rdparty/resonance-audio/LICENSE %{buildroot}/usr/share/package-licenses/qt6multimedia/47b573e3824cd5e02a1a3ae99e2735b49e0256e4 || :
export GOAMD64=v2
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qabstractvideobuffer_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qaudiodecoder_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qaudiodevice_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qaudioengine_pulse_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qaudiohelpers_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qaudiostatemachine_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qaudiostatemachineutils_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qaudiosystem_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qcamera_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qcameradevice_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qcapturablewindow_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qerrorinfo_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qgstreamer_platformspecificinterface_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qimagevideobuffer_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qmaybe_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qmediacapturesession_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qmediaplayer_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qmediarecorder_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qmediastoragelocation_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qmemoryvideobuffer_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qmultimediautils_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qplatformaudiodecoder_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qplatformaudioinput_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qplatformaudiooutput_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qplatformaudioresampler_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qplatformcamera_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qplatformcapturablewindows_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qplatformimagecapture_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qplatformmediacapture_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qplatformmediadevices_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qplatformmediaformatinfo_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qplatformmediaintegration_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qplatformmediaplayer_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qplatformmediaplugin_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qplatformmediarecorder_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qplatformsurfacecapture_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qplatformvideodevices_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qplatformvideosink_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qplatformvideosource_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qpulseaudiodevice_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qpulseaudiomediadevices_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qpulseaudiosink_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qpulseaudiosource_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qpulsehelpers_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qsamplecache_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qsymbolsresolveutils_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qtmultimedia-config_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qtmultimediaglobal_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qvideoframe_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qvideoframeconversionhelper_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qvideoframeconverter_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qvideooutputorientationhandler_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qvideotexturehelper_p.h
/usr/include/QtMultimedia/6.7.2/QtMultimedia/private/qvideowindow_p.h
/usr/include/QtMultimedia/QAudio
/usr/include/QtMultimedia/QAudioBuffer
/usr/include/QtMultimedia/QAudioDecoder
/usr/include/QtMultimedia/QAudioDevice
/usr/include/QtMultimedia/QAudioFormat
/usr/include/QtMultimedia/QAudioFrame
/usr/include/QtMultimedia/QAudioInput
/usr/include/QtMultimedia/QAudioOutput
/usr/include/QtMultimedia/QAudioSink
/usr/include/QtMultimedia/QAudioSource
/usr/include/QtMultimedia/QCamera
/usr/include/QtMultimedia/QCameraDevice
/usr/include/QtMultimedia/QCameraFormat
/usr/include/QtMultimedia/QCapturableWindow
/usr/include/QtMultimedia/QImageCapture
/usr/include/QtMultimedia/QMediaCaptureSession
/usr/include/QtMultimedia/QMediaDevices
/usr/include/QtMultimedia/QMediaFormat
/usr/include/QtMultimedia/QMediaMetaData
/usr/include/QtMultimedia/QMediaPlayer
/usr/include/QtMultimedia/QMediaRecorder
/usr/include/QtMultimedia/QMediaTimeRange
/usr/include/QtMultimedia/QScreenCapture
/usr/include/QtMultimedia/QSoundEffect
/usr/include/QtMultimedia/QVideoFrame
/usr/include/QtMultimedia/QVideoFrameFormat
/usr/include/QtMultimedia/QVideoSink
/usr/include/QtMultimedia/QWaveDecoder
/usr/include/QtMultimedia/QWindowCapture
/usr/include/QtMultimedia/QtAudio
/usr/include/QtMultimedia/QtMultimedia
/usr/include/QtMultimedia/QtMultimediaDepends
/usr/include/QtMultimedia/QtMultimediaVersion
/usr/include/QtMultimedia/qaudio.h
/usr/include/QtMultimedia/qaudiobuffer.h
/usr/include/QtMultimedia/qaudiodecoder.h
/usr/include/QtMultimedia/qaudiodevice.h
/usr/include/QtMultimedia/qaudioformat.h
/usr/include/QtMultimedia/qaudioinput.h
/usr/include/QtMultimedia/qaudiooutput.h
/usr/include/QtMultimedia/qaudiosink.h
/usr/include/QtMultimedia/qaudiosource.h
/usr/include/QtMultimedia/qcamera.h
/usr/include/QtMultimedia/qcameradevice.h
/usr/include/QtMultimedia/qcapturablewindow.h
/usr/include/QtMultimedia/qimagecapture.h
/usr/include/QtMultimedia/qmediacapturesession.h
/usr/include/QtMultimedia/qmediadevices.h
/usr/include/QtMultimedia/qmediaenumdebug.h
/usr/include/QtMultimedia/qmediaformat.h
/usr/include/QtMultimedia/qmediametadata.h
/usr/include/QtMultimedia/qmediaplayer.h
/usr/include/QtMultimedia/qmediarecorder.h
/usr/include/QtMultimedia/qmediatimerange.h
/usr/include/QtMultimedia/qscreencapture.h
/usr/include/QtMultimedia/qsoundeffect.h
/usr/include/QtMultimedia/qtaudio.h
/usr/include/QtMultimedia/qtmultimedia-config.h
/usr/include/QtMultimedia/qtmultimediaexports.h
/usr/include/QtMultimedia/qtmultimediaglobal.h
/usr/include/QtMultimedia/qtmultimediaversion.h
/usr/include/QtMultimedia/qtvideo.h
/usr/include/QtMultimedia/qvideoframe.h
/usr/include/QtMultimedia/qvideoframeformat.h
/usr/include/QtMultimedia/qvideosink.h
/usr/include/QtMultimedia/qwavedecoder.h
/usr/include/QtMultimedia/qwindowcapture.h
/usr/include/QtMultimediaQuick/6.7.2/QtMultimediaQuick/private/qquickimagecapture_p.h
/usr/include/QtMultimediaQuick/6.7.2/QtMultimediaQuick/private/qquickimagepreviewprovider_p.h
/usr/include/QtMultimediaQuick/6.7.2/QtMultimediaQuick/private/qquickmediaplayer_p.h
/usr/include/QtMultimediaQuick/6.7.2/QtMultimediaQuick/private/qquickscreencapture_p.h
/usr/include/QtMultimediaQuick/6.7.2/QtMultimediaQuick/private/qquicksoundeffect_p.h
/usr/include/QtMultimediaQuick/6.7.2/QtMultimediaQuick/private/qquickvideooutput_p.h
/usr/include/QtMultimediaQuick/6.7.2/QtMultimediaQuick/private/qsgvideonode_p.h
/usr/include/QtMultimediaQuick/6.7.2/QtMultimediaQuick/private/qsgvideotexture_p.h
/usr/include/QtMultimediaQuick/6.7.2/QtMultimediaQuick/private/qtmultimediaquickglobal_p.h
/usr/include/QtMultimediaQuick/6.7.2/QtMultimediaQuick/private/qtmultimediaquicktypes_p.h
/usr/include/QtMultimediaQuick/QtMultimediaQuick
/usr/include/QtMultimediaQuick/QtMultimediaQuickDepends
/usr/include/QtMultimediaQuick/QtMultimediaQuickVersion
/usr/include/QtMultimediaQuick/qtmultimediaquickexports.h
/usr/include/QtMultimediaQuick/qtmultimediaquickversion.h
/usr/include/QtMultimediaWidgets/6.7.2/QtMultimediaWidgets/private/qvideowidget_p.h
/usr/include/QtMultimediaWidgets/QGraphicsVideoItem
/usr/include/QtMultimediaWidgets/QVideoWidget
/usr/include/QtMultimediaWidgets/QtMultimediaWidgets
/usr/include/QtMultimediaWidgets/QtMultimediaWidgetsDepends
/usr/include/QtMultimediaWidgets/QtMultimediaWidgetsVersion
/usr/include/QtMultimediaWidgets/qgraphicsvideoitem.h
/usr/include/QtMultimediaWidgets/qtmultimediawidgetsexports.h
/usr/include/QtMultimediaWidgets/qtmultimediawidgetsglobal.h
/usr/include/QtMultimediaWidgets/qtmultimediawidgetsversion.h
/usr/include/QtMultimediaWidgets/qvideowidget.h
/usr/include/QtSpatialAudio/6.7.2/QtSpatialAudio/private/qambisonicdecoder_p.h
/usr/include/QtSpatialAudio/6.7.2/QtSpatialAudio/private/qambisonicdecoderdata_p.h
/usr/include/QtSpatialAudio/6.7.2/QtSpatialAudio/private/qaudioengine_p.h
/usr/include/QtSpatialAudio/6.7.2/QtSpatialAudio/private/qaudioroom_p.h
/usr/include/QtSpatialAudio/6.7.2/QtSpatialAudio/private/qtspatialaudioglobal_p.h
/usr/include/QtSpatialAudio/QAmbientSound
/usr/include/QtSpatialAudio/QAudioEngine
/usr/include/QtSpatialAudio/QAudioListener
/usr/include/QtSpatialAudio/QAudioRoom
/usr/include/QtSpatialAudio/QSpatialSound
/usr/include/QtSpatialAudio/QtSpatialAudio
/usr/include/QtSpatialAudio/QtSpatialAudioDepends
/usr/include/QtSpatialAudio/QtSpatialAudioVersion
/usr/include/QtSpatialAudio/qambientsound.h
/usr/include/QtSpatialAudio/qaudioengine.h
/usr/include/QtSpatialAudio/qaudiolistener.h
/usr/include/QtSpatialAudio/qaudioroom.h
/usr/include/QtSpatialAudio/qspatialsound.h
/usr/include/QtSpatialAudio/qtspatialaudioexports.h
/usr/include/QtSpatialAudio/qtspatialaudioglobal.h
/usr/include/QtSpatialAudio/qtspatialaudioversion.h
/usr/lib64/cmake/Qt6/FindAVFoundation.cmake
/usr/lib64/cmake/Qt6/FindFFmpeg.cmake
/usr/lib64/cmake/Qt6/FindGObject.cmake
/usr/lib64/cmake/Qt6/FindGStreamer.cmake
/usr/lib64/cmake/Qt6/FindMMRenderer.cmake
/usr/lib64/cmake/Qt6/FindMMRendererCore.cmake
/usr/lib64/cmake/Qt6/FindVAAPI.cmake
/usr/lib64/cmake/Qt6/FindWMF.cmake
/usr/lib64/cmake/Qt6/FindWrapBundledResonanceAudioConfigExtra.cmake
/usr/lib64/cmake/Qt6/FindWrapPulseAudio.cmake
/usr/lib64/cmake/Qt6BuildInternals/StandaloneTests/QtMultimediaTestsConfig.cmake
/usr/lib64/cmake/Qt6BundledResonanceAudio/Qt6BundledResonanceAudioAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6BundledResonanceAudio/Qt6BundledResonanceAudioConfig.cmake
/usr/lib64/cmake/Qt6BundledResonanceAudio/Qt6BundledResonanceAudioConfigVersion.cmake
/usr/lib64/cmake/Qt6BundledResonanceAudio/Qt6BundledResonanceAudioConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6BundledResonanceAudio/Qt6BundledResonanceAudioTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Qt6BundledResonanceAudio/Qt6BundledResonanceAudioTargets.cmake
/usr/lib64/cmake/Qt6BundledResonanceAudio/Qt6BundledResonanceAudioVersionlessTargets.cmake
/usr/lib64/cmake/Qt6Multimedia/Qt6MultimediaAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6Multimedia/Qt6MultimediaConfig.cmake
/usr/lib64/cmake/Qt6Multimedia/Qt6MultimediaConfigVersion.cmake
/usr/lib64/cmake/Qt6Multimedia/Qt6MultimediaConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6Multimedia/Qt6MultimediaDependencies.cmake
/usr/lib64/cmake/Qt6Multimedia/Qt6MultimediaPlugins.cmake
/usr/lib64/cmake/Qt6Multimedia/Qt6MultimediaTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Qt6Multimedia/Qt6MultimediaTargets.cmake
/usr/lib64/cmake/Qt6Multimedia/Qt6MultimediaVersionlessTargets.cmake
/usr/lib64/cmake/Qt6MultimediaQuickPrivate/Qt6MultimediaQuickPrivateAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6MultimediaQuickPrivate/Qt6MultimediaQuickPrivateConfig.cmake
/usr/lib64/cmake/Qt6MultimediaQuickPrivate/Qt6MultimediaQuickPrivateConfigVersion.cmake
/usr/lib64/cmake/Qt6MultimediaQuickPrivate/Qt6MultimediaQuickPrivateConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6MultimediaQuickPrivate/Qt6MultimediaQuickPrivateDependencies.cmake
/usr/lib64/cmake/Qt6MultimediaQuickPrivate/Qt6MultimediaQuickPrivateTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Qt6MultimediaQuickPrivate/Qt6MultimediaQuickPrivateTargets.cmake
/usr/lib64/cmake/Qt6MultimediaQuickPrivate/Qt6MultimediaQuickPrivateVersionlessTargets.cmake
/usr/lib64/cmake/Qt6MultimediaWidgets/Qt6MultimediaWidgetsAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6MultimediaWidgets/Qt6MultimediaWidgetsConfig.cmake
/usr/lib64/cmake/Qt6MultimediaWidgets/Qt6MultimediaWidgetsConfigVersion.cmake
/usr/lib64/cmake/Qt6MultimediaWidgets/Qt6MultimediaWidgetsConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6MultimediaWidgets/Qt6MultimediaWidgetsDependencies.cmake
/usr/lib64/cmake/Qt6MultimediaWidgets/Qt6MultimediaWidgetsTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Qt6MultimediaWidgets/Qt6MultimediaWidgetsTargets.cmake
/usr/lib64/cmake/Qt6MultimediaWidgets/Qt6MultimediaWidgetsVersionlessTargets.cmake
/usr/lib64/cmake/Qt6Qml/QmlPlugins/Qt6quickmultimediaAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6Qml/QmlPlugins/Qt6quickmultimediaConfig.cmake
/usr/lib64/cmake/Qt6Qml/QmlPlugins/Qt6quickmultimediaConfigVersion.cmake
/usr/lib64/cmake/Qt6Qml/QmlPlugins/Qt6quickmultimediaConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6Qml/QmlPlugins/Qt6quickmultimediaTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Qt6Qml/QmlPlugins/Qt6quickmultimediaTargets.cmake
/usr/lib64/cmake/Qt6SpatialAudio/Qt6SpatialAudioAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6SpatialAudio/Qt6SpatialAudioConfig.cmake
/usr/lib64/cmake/Qt6SpatialAudio/Qt6SpatialAudioConfigVersion.cmake
/usr/lib64/cmake/Qt6SpatialAudio/Qt6SpatialAudioConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6SpatialAudio/Qt6SpatialAudioDependencies.cmake
/usr/lib64/cmake/Qt6SpatialAudio/Qt6SpatialAudioTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Qt6SpatialAudio/Qt6SpatialAudioTargets.cmake
/usr/lib64/cmake/Qt6SpatialAudio/Qt6SpatialAudioVersionlessTargets.cmake
/usr/lib64/libQt6Multimedia.prl
/usr/lib64/libQt6Multimedia.so
/usr/lib64/libQt6MultimediaQuick.prl
/usr/lib64/libQt6MultimediaQuick.so
/usr/lib64/libQt6MultimediaWidgets.prl
/usr/lib64/libQt6MultimediaWidgets.so
/usr/lib64/libQt6SpatialAudio.prl
/usr/lib64/libQt6SpatialAudio.so
/usr/lib64/pkgconfig/Qt6Multimedia.pc
/usr/lib64/pkgconfig/Qt6MultimediaWidgets.pc
/usr/lib64/pkgconfig/Qt6SpatialAudio.pc
/usr/lib64/qt6/mkspecs/modules/qt_lib_multimedia.pri
/usr/lib64/qt6/mkspecs/modules/qt_lib_multimedia_private.pri
/usr/lib64/qt6/mkspecs/modules/qt_lib_multimediaquick_private.pri
/usr/lib64/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri
/usr/lib64/qt6/mkspecs/modules/qt_lib_multimediawidgets_private.pri
/usr/lib64/qt6/mkspecs/modules/qt_lib_spatialaudio.pri
/usr/lib64/qt6/mkspecs/modules/qt_lib_spatialaudio_private.pri

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libQt6Multimedia.so.6.7.2
/V3/usr/lib64/libQt6MultimediaQuick.so.6.7.2
/V3/usr/lib64/libQt6MultimediaWidgets.so.6.7.2
/V3/usr/lib64/libQt6SpatialAudio.so.6.7.2
/V3/usr/lib64/qt6/qml/QtMultimedia/libquickmultimediaplugin.so
/usr/lib64/libQt6Multimedia.so.6
/usr/lib64/libQt6Multimedia.so.6.7.2
/usr/lib64/libQt6MultimediaQuick.so.6
/usr/lib64/libQt6MultimediaQuick.so.6.7.2
/usr/lib64/libQt6MultimediaWidgets.so.6
/usr/lib64/libQt6MultimediaWidgets.so.6.7.2
/usr/lib64/libQt6SpatialAudio.so.6
/usr/lib64/libQt6SpatialAudio.so.6.7.2
/usr/lib64/qt6/metatypes/qt6multimedia_relwithdebinfo_metatypes.json
/usr/lib64/qt6/metatypes/qt6multimediaquickprivate_relwithdebinfo_metatypes.json
/usr/lib64/qt6/metatypes/qt6multimediawidgets_relwithdebinfo_metatypes.json
/usr/lib64/qt6/metatypes/qt6spatialaudio_relwithdebinfo_metatypes.json
/usr/lib64/qt6/modules/Multimedia.json
/usr/lib64/qt6/modules/MultimediaQuickPrivate.json
/usr/lib64/qt6/modules/MultimediaWidgets.json
/usr/lib64/qt6/modules/SpatialAudio.json
/usr/lib64/qt6/qml/QtMultimedia/Video.qml
/usr/lib64/qt6/qml/QtMultimedia/libquickmultimediaplugin.so
/usr/lib64/qt6/qml/QtMultimedia/plugins.qmltypes
/usr/lib64/qt6/qml/QtMultimedia/qmldir

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/qt6multimedia/2bc71d48cf227830dff9a8d2a09ae79dbc997507
/usr/share/package-licenses/qt6multimedia/47b573e3824cd5e02a1a3ae99e2735b49e0256e4
/usr/share/package-licenses/qt6multimedia/7713a1753ce88f2c7e6b054ecc8e4c786df76300
/usr/share/package-licenses/qt6multimedia/793b93301a29a830d8b40b3cbfaedec58193a291
/usr/share/package-licenses/qt6multimedia/79453f55fa8ee32d7b95581473edcbfd043e088f
/usr/share/package-licenses/qt6multimedia/9cf097120d3d9eea0e9790d7d44ae80e6231a35a
/usr/share/package-licenses/qt6multimedia/c70af14df11e3908dfc10397b1ba4b1f346661f3
/usr/share/package-licenses/qt6multimedia/dc8f2e570bf431427dbc3bab9d4d551b53a60208
/usr/share/package-licenses/qt6multimedia/edf9e52983e1225976cdb134d78a286224acc9f3
